name: Test and Deploy Bash Script

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Bash script tests
      run: |
        chmod +x ./my_script.sh &&  ./my_script.sh

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug SSH connection
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH Connection Successful'"

    - name: Copy files to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: private_key
        port: 22
        source: "."
        target: "/root"

    - name: Run script on remote server
      run: |
        ssh -o StrictHostKeyChecking=no user@remote-server 'bash /root/my_script.sh'
